name: Run Release deb packages
run-name: ${{ github.actor }} runs release rooftop deb packages
on:
  push:
    tags:
      - '*.*.*'
jobs:
  arm64:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - run: docker build --build-arg VERSION=${{ env.RELEASE_VERSION }} --build-arg ARCHITECTURE=arm64 . -t deb_creator:latest
      - run: docker run -v $(pwd)/build:/output deb_creator:latest
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: orbit-tools_${{ env.RELEASE_VERSION }}_arm64.deb
          path: build/orbit-tools_${{ env.RELEASE_VERSION }}_arm64.deb
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/*.deb
  amd64:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - run: docker build --build-arg VERSION=${{ env.RELEASE_VERSION }} --build-arg ARCHITECTURE=amd64 . -t deb_creator:latest
      - run: docker run -v $(pwd)/build::/output deb_creator:latest
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: orbit-tools_${{ env.RELEASE_VERSION }}_amd64.deb
          path: build/orbit-tools_${{ env.RELEASE_VERSION }}_amd64.deb
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/*.deb